import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import type { QuoteResult } from "./types"

export function exportQuotePDF(result: QuoteResult) {
  const doc = new jsPDF()
  const sortedQuotes = [...result.quotes].sort(
    (a, b) => a.annualPremium - b.annualPremium
  )
  const bestQuote = sortedQuotes.find((q) => q.isBestValue) || sortedQuotes[0]

  // Header
  doc.setFontSize(22)
  doc.setTextColor(214, 40, 40) // lava-red
  doc.text("LAVA Training Rater", 14, 22)

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text("Insurance Quote Comparison Report", 14, 30)

  // Line separator
  doc.setDrawColor(214, 40, 40)
  doc.setLineWidth(0.5)
  doc.line(14, 34, 196, 34)

  // Quote Info
  doc.setFontSize(11)
  doc.setTextColor(40, 40, 40)
  const quoteType = result.type === "auto" ? "Auto" : "Homeowners"
  doc.text(`Quote Type: ${quoteType} Insurance`, 14, 44)
  doc.text(`Customer: ${result.customerName}`, 14, 51)
  doc.text(`VA: ${result.vaName}`, 14, 58)
  doc.text(
    `Date: ${new Date(result.createdAt).toLocaleDateString()}`,
    14,
    65
  )
  doc.text(`Quote ID: ${result.id}`, 14, 72)

  // Summary Box
  doc.setFillColor(255, 107, 53) // lava-orange
  doc.roundedRect(14, 80, 182, 22, 3, 3, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(12)
  doc.text("Best Value", 20, 90)
  doc.setFontSize(14)
  doc.text(
    `${bestQuote.carrierName} - $${bestQuote.annualPremium.toLocaleString()}/year ($${Math.round(bestQuote.annualPremium / 12).toLocaleString()}/mo)`,
    20,
    98
  )

  // Comparison Table
  const tableData = sortedQuotes.map((q, i) => [
    `#${i + 1}`,
    q.carrierName,
    `$${q.annualPremium.toLocaleString()}`,
    `$${Math.round(q.annualPremium / 12).toLocaleString()}`,
    q.discountsApplied.join(", ") || "None",
    q.isBestValue ? "BEST" : "",
  ])

  autoTable(doc, {
    startY: 110,
    head: [["Rank", "Carrier", "Annual", "Monthly", "Discounts", ""]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [214, 40, 40],
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [40, 40, 40],
    },
    alternateRowStyles: {
      fillColor: [255, 245, 238],
    },
    columnStyles: {
      0: { cellWidth: 14, halign: "center" },
      2: { halign: "right", fontStyle: "bold" },
      3: { halign: "right" },
      5: {
        halign: "center",
        fontStyle: "bold",
        textColor: [214, 40, 40],
      },
    },
  })

  // Coverage Details table
  const finalY =
    (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable
      .finalY + 10

  if (finalY < 240) {
    doc.setFontSize(12)
    doc.setTextColor(40, 40, 40)
    doc.text("Coverage Details - Best Value Carrier", 14, finalY)

    const coverageData = bestQuote.coverageDetails.map((d) => [
      d.label,
      d.value,
    ])

    autoTable(doc, {
      startY: finalY + 5,
      head: [["Coverage", "Amount"]],
      body: coverageData,
      theme: "grid",
      headStyles: {
        fillColor: [247, 127, 0],
        textColor: [255, 255, 255],
        fontSize: 9,
      },
      bodyStyles: { fontSize: 9 },
    })
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      "Generated by LAVA Training Rater - For Training Purposes Only",
      14,
      287
    )
    doc.text(`Page ${i} of ${pageCount}`, 180, 287)
  }

  // Save
  const filename = `LAVA_${quoteType}_Quote_${result.customerName.replace(/\s+/g, "_")}_${new Date(result.createdAt).toISOString().split("T")[0]}.pdf`
  doc.save(filename)
}
